### ISSUE TITLE
How do I setup lemonbar?

### ISSUE THREAD

**Issue by SisyphusIsntHappy** [BeyondMagic/MaGiCK#1]
Could you add your lemonbar config to the repo?

I have already patched dwm with anybar and ipc patch, I don't how know how to proceed.

**Comment by BeyondMagic** [comment]
I will update this for the XResources files, but the bars are in a different repository.

https://github.com/BeyondMagic/scripts/tree/master/bars

Install this lemonbar as well:

https://github.com/PH111P/bar

Install `xgetres` from the AUR if you're on Arch for [XResources](https://wiki.archlinux.org/title/x_resources) support, or https://github.com/tamirzb/xgetres

And each script and bar itself is pretty much documented in the code, I would recommend you first remove the external scripts and external commands first for each bar and then slowly add each one as they need external commands to work and you go through them to see if can work just fine.

![image](https://user-images.githubusercontent.com/51831435/142053327-83b9df8a-3912-4bce-aee0-c713e7592e46.png)

Of course change the fonts, too.

![image](https://user-images.githubusercontent.com/51831435/142053417-8e1f6c69-fe4e-43dd-b6df-26d16cd48a87.png)

I will help out with the problems you may have, as lemonbars are actually pretty, pretty difficult to work with. But if you already tried working with them, you may be fine with it.

**Comment by BeyondMagic** [comment]
Lemonbar was removed and the configuration is now settled on EWW -- as in so far I believe in the long-term it will be a decision that will be better for anyone.
